# Site settings
title: /* HACK */
email: annie.cherk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Beep Beep Boop Boop
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://anniecherkaev.com" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
